### ISSUE TITLE
ProductPropertyValues are not bound to PropertyGroups

### ISSUE THREAD

**Issue by pigletto** [diefenbach/django-lfs#150]
ProductPropertyValues are not bound to PropertyGroups what causes wrong behaviour when two PropertyGroups containing same Property are bound to single Product. 
At property Edit form it'll look like you have two separate properties in two different groups, while in fact it is just one ProductPropertyValue.

I already have a branch that fixes it but it's not yet pushed to github as its needs merge with recent master changes. For now this issue is just for reference, until I have my branch ready.

**Comment by diefenbach** [comment]
Fixed.
