### ISSUE TITLE
Pillow dependencies to image processing libraries  are not mentioned in installation documents

### ISSUE THREAD

**Issue by janihur** [diefenbach/django-lfs#156]
Pillow dependencies to image processing libraries are not mentioned in installation documents:
http://docs.getlfs.com/en/latest/introduction/installation.html

See chapter External dependencies on: http://pillow.readthedocs.org/en/latest/installation.html

In Ubuntu 14.04.1 LTS I issued the following command to get support for JPG and PNG:

```
$ sudo apt-get -y install libjpeg8-dev zlib1g-dev
```

I think this would be better to mention in a new External Dependencies chapter in LFS installation guide. The same chapter could also include the content of http://docs.getlfs.com/en/latest/misc/trouble_shooting.html#trouble-shooting-installation.

**Comment by diefenbach** [comment]
Fixed. 9fc0a23accadd73ccf8c1cde33a4c3898e7c1202
