### ISSUE TITLE
navigation shows nonactive products

### ISSUE THREAD

**Issue by McQuak** [diefenbach/django-lfs#161]
Hello

1. navigation on product online page ((  << Previous product - 1 of 2 - Next product >> ))
ignore if product ai active or not and count all of them - by this navigation you can show page with non active product

2. non active product is accessible by typing its url 
*on the page is not any message informing customer that product is not possible to order 
*order button is active and raise 404 page

Boths errors are tested on demoshop and also on version 0.9

**Comment by pigletto** [comment]
This only happens when you're logged in as manager and I consider it correct behaviour in such situation. Anyway, thanks for reporting!
