### ISSUE TITLE
product overview deletes all prices

### ISSUE THREAD

**Issue by McQuak** [diefenbach/django-lfs#164]
LFS 0.9
save button on Products overview page deletes all prices include action prices on page - prices of products hidden by filter are not deleted

changed price is sometimes  saved but sometimes is deleted too

**Comment by pigletto** [comment]
Unfortunatelly I was not able to reproduce this issue. Can you please find out and provide more detailed description how to reproduce that?

What do you mean by 'deleted' prices? Are these set to 0? Isn't it related to decimal separator, eg. '.' or ','?

**Comment by McQuak** [comment]
pigletto you are right - problem is with "," and "." 

Prices with "." or without decimals are correctly saved
I use czech locales and prices in overview are displayed with ","  - this is reason why prices are deleted to 0.

So problem is that prices are not converted from locales

Is it difficult to fix it?

**Comment by pigletto** [comment]
Fixed. Thanks for reporting!
