### ISSUE TITLE
Products overview filter doesn't remember settings

### ISSUE THREAD

**Issue by McQuak** [diefenbach/django-lfs#165]
Filter on Products overview page doesn't remember settings after saving changes - it will be very uncomfortable to use it

**Comment by pigletto** [comment]
Cannot reproduce that. I've set filter and then clicked 'Save' button. Popup in the right top corner appeared saying that 'Products were saved'. What is happening on your 'end'?

**Comment by McQuak** [comment]
1. I set filter for 10 products 
2. I change some data - price for example - and save
3. data are save, popup 'Products were saved' is displayed
4. filter is still with settings for 10 products, but displayed are all products
5. you must press "Filter products" to filter them again or go to ather page and then back to Product overviews

This is same on demoshop

**Comment by pigletto** [comment]
OK, got it. Seems the problem is only with 'Amount' field. Other filters are remembered

**Comment by pigletto** [comment]
Fixed, thanks for reporting!
