### ISSUE TITLE
wrong list of goods after save product

### ISSUE THREAD

**Issue by McQuak** [diefenbach/django-lfs#172]
Go to Catalog / Products - go to second page of products and choose some product - make changes and save. Data are correctly saved, but on the left is list of products from first page even that navigation (on top of list) still shows second page. You must go to previous page and back to get correct list of products

Issue is similar to https://github.com/diefenbach/django-lfs/issues/169

**Comment by pigletto** [comment]
Resolved, thanks for reporting!
