### ISSUE TITLE
Adding shipping/invoice countries

### ISSUE THREAD

**Issue by Happy-Ferret** [diefenbach/django-lfs#174]
According to the Getting Started guide, I should be able to set the shipping and invoice, as well as the default shipping country (under "Shop -> Preferences -> Default Values"). 

However, the only choice available to me for all three is "USA". 

How would I go about adding more countries?

**Comment by diefenbach** [comment]
Go to Django's admin / countries and add the countries you need.

K.

--
IQ++
Tel: +49 361 / 6636700
Fax: +49 361 / 6636702
Mail: kai.diefenbach@iqpp.de
Web: http://www.iqpp.de
Skype: kai.diefenbach
