### ISSUE TITLE
Do we need 0005 and 0006 migrations in catalog app?

### ISSUE THREAD

**Issue by DNX** [diefenbach/django-lfs#179]
Do we need [0005](https://github.com/diefenbach/django-lfs/blob/master/lfs/catalog/migrations/0005_auto__update_property__table.py) and [0006](https://github.com/diefenbach/django-lfs/blob/master/lfs/catalog/migrations/0006_set_variants_to_true.py) migrations in catalog app? We have [migrate_to_08()](https://github.com/diefenbach/django-lfs/blob/master/lfs/core/management/commands/lfs_migrate.py#L565) that do the same before this migrations so South will fail here.

**Comment by pigletto** [comment]
Seems you're right, not sure why it appeared there. I've commented it out because we have newer migrations now.

**Comment by diefenbach** [comment]
This throws an error if you create a new database from scratch.
