### ISSUE TITLE
Orders are removed if Shipment method is removed

### ISSUE THREAD

**Issue by pigletto** [diefenbach/django-lfs#182]
When we remove Shipment method that is assigned to some Orders then these Orders are also removed.

Similarly, if we remove Tax (product tax) object then orders are removed (not sure yet why, possibly it causes cascade removal of shipment/payment methods and then Orders).

Seems that we should have separate models to store information about PaymentMethod/ShipmentMethod/Tax as it was when Order was submitted.

**Comment by diefenbach** [comment]
Yes, either we store the information within extra instances or models or we just save the name of the shipping/payment method as it was when the order has been submitted.

Not sure whether we need the whole information on an order.

What do you think?
