### ISSUE TITLE
How to display euro symbol for prices?

### ISSUE THREAD

**Issue by pfennema** [diefenbach/django-lfs#186]
Hello all,

I'd like to display prices with a euro symbol instead of 'EUR'. What I tried so far is the following in lfs_project/settings:
LANGUAGE_CODE = 'nl-NL'
USE_I18N = True
USE_L10N = True

And I added to MIDDLEWARE_CLASSES  'django.middleware.locale.LocaleMiddleware'

It now displays EUR, but i'd like to display €.

What do I miss?

Thanks, Paul

**Comment by pigletto** [comment]
Try the following:
LANGUAGE_CODE = 'nl'
LFS_LOCALE = "nl_NL.UTF-8"
USE_I18N = True
USE_L10N = True

and then you can also switch on/off the checkbox in the management panel: Shop -> Preferences -> Default values -> Use international currency codes:

**Comment by pfennema** [comment]
When changing the LANGUAGE_CODE to 'nl' and the LFS_LOCALE to nl_NL.UTF-8 (it was nl_NL) and switch off the checkbox in Default values, I get an 'Eu' symbol.
I forgot to mention that I indeed changed the Default values on and off before. Thanks for the suggestion though!
