### ISSUE TITLE
Why is the object left None?

### ISSUE THREAD

**Issue by parsadevloper** [diefenbach/django-lfs#219]
https://github.com/diefenbach/django-lfs/blob/064367c67fe66c0779a55660ea35fdfc5cebd447/lfs/caching/utils.py#L84

hi Mr.
`    object = cache.get(cache_key)
    object = None `
Why is the object left None?

**Comment by diefenbach** [comment]
That's a bug, thx!

**Comment by parsadevloper** [comment]
thank you for developing this great project. I learned a lot from it.

**Comment by diefenbach** [comment]
Thx!
