### ISSUE TITLE
git cloning fails during buildout

### ISSUE THREAD

**Issue by harihara** [diefenbach/django-lfs#30]
hari@hariT410:/projects/lfs-buildout-development$ bin/buildout -v
Installing 'mr.developer'.
We have the best distribution that satisfies 'mr.developer'.
Picked: mr.developer = 1.21
mr.developer: Queued 'lfs' for checkout.
mr.developer: Queued 'lfs_bench' for checkout.
mr.developer: Queued 'lfs_contact' for checkout.
mr.developer: Queued 'lfs_order_numbers' for checkout.
mr.developer: Queued 'lfs_paypal' for checkout.
mr.developer: Queued 'lfs_rest' for checkout.
mr.developer: Queued 'lfs_theme' for checkout.
mr.developer: Queued 'portlets' for checkout.
mr.developer: Queued 'reviews' for checkout.
mr.developer: Cloned 'lfs' with git.
mr.developer: git cloning of 'lfs' failed.
mr.developer: Permission denied (publickey).
mr.developer: fatal: The remote end hung up unexpectedly
mr.developer: 
mr.developer: Cloned 'lfs_bench' with git.
mr.developer: git cloning of 'lfs_bench' failed.
mr.developer: Permission denied (publickey).
mr.developer: fatal: The remote end hung up unexpectedly
mr.developer: 
mr.developer: Cloned 'lfs_paypal' with git.
mr.developer: git cloning of 'lfs_paypal' failed.
mr.developer: Permission denied (publickey).
mr.developer: fatal: The remote end hung up unexpectedly
mr.developer: 
mr.developer: Cloned 'lfs_contact' with git.
mr.developer: git cloning of 'lfs_contact' failed.
mr.developer: Permission denied (publickey).
mr.developer: fatal: The remote end hung up unexpectedly
mr.developer: 
mr.developer: Cloned 'lfs_order_numbers' with git.
mr.developer: git cloning of 'lfs_order_numbers' failed.
mr.developer: Permission denied (publickey).
mr.developer: fatal: The remote end hung up unexpectedly
mr.developer: 
mr.developer: There have been errors, see messages above.
hari@hariT410:/projects/lfs-buildout-development$

**Comment by XUHAOLIANG2014** [comment]
how can i upload my ssh key？

**Comment by linuxmyjob** [comment]
how to upload my ssh key ?
