### ISSUE TITLE
sitemap.py and multi variant products

### ISSUE THREAD

**Issue by pierreNomazy** [diefenbach/django-lfs#49]
Sitemap which include multi_variant product lead to weakness SEO for the main product. In the best case (but not all cases) google robot will not index your multi variant products. can be check in tools for webmasters.
So I advice to change in sitemaps.py, line 19 :         return Product.objects.filter(sub_type__in=[0,1], active='TRUE')
OR for having priority different for sub_type=0 and 1 : 
class ProductSitemap0(Sitemap): with filter(sub_type=0, active='TRUE')
class ProductSitemap1(Sitemap): with filter(sub_type=1, active='TRUE')
and in urls.py : import both classes and :  url(r'^sitemap.xml$', 'sitemap', {'sitemaps': {"products0": ProductSitemap0,"products1": ProductSitemap1, "categories": CategorySitemap, "pages": PageSitemap, "shop": ShopSitemap}})

Pierre

**Comment by diefenbach** [comment]
Fixed.
