### ISSUE TITLE
Wrong German translation

### ISSUE THREAD

**Issue by eambrosch** [diefenbach/django-lfs#50]
# : templates/lfs/customer/base.html:23

msgid "Change addresses"
msgstr "Addressen ändern"

-> Should be: "Adressdaten ändern" or "Adresse ändern"
# : templates/lfs/customer/base.html:17 templates/lfs/customer/password.html:50

msgid "Change password"
msgstr "Password ändern"

-> Should be: "Passwort ändern"

**Comment by diefenbach** [comment]
Fixed. db05fd5cb32e74bcb3e86beb9ac9474366107d2e
